apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-tracking-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-tracking
  template:
    metadata:
      labels:
        app: live-tracking
    spec:
      containers:
        - name: live-tracking
          image: prnv404/live-tracking
---
apiVersion: v1
kind: Service
metadata:
  name: live-tracking-srv
spec:
  selector:
    app: live-tracking
  ports:
    - name: live-tracking
      protocol: TCP
      port: 3000
      targetPort: 3000
