apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-operators-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-operators
  template:
    metadata:
      labels:
        app: private-operators
    spec:
      containers:
        - name: private-operators
          image: prnv404/private-operators
---
apiVersion: v1
kind: Service
metadata:
  name: private-operators-srv
spec:
  selector:
    app: private-operators
  ports:
    - name: private-operators
      protocol: TCP
      port: 3000
      targetPort: 3000
