name: deploy-private-operators

on:
  push:
    branches:
      - master
    paths:
      - 'private-operators/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd private-operators  && docker build -t prnv404/private-operators .
      - run: docker push prnv404/private-operators
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-27-2-do-0-blr1-1690173421190
      - run: kubectl rollout restart deployment private-operators-depl
