name: tests-state-operators

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'state-operators/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd state-operators && npm install && npm run test:ci
